spring:
  datasource:
    url: jdbc:mysql://dbshopticket.mysql.database.azure.com:3306/shopticket?useSSL=true
    username: martina
    password: Casola7.
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.MySQLInnoDBDialect


server:
  port: 8080


azure:
  key-vault:
    enabled: true
    uri: https://credenzialishopticket.vault.azure.net/
    client-id: 731a04f7-bd4d-488a-965e-3f2484cbfd04
    ##client-key: V.q~NOT7o.KH5A4n2G9fbO3Rl4K~yTvx-z
    tenant-id: 2fcfe26a-bb62-46b0-b1e3-28f9da0c45fd