spring:
  datasource:
    url: jdbc:mysql://dbshopticket.mysql.database.azure.com:3306/shopticket?useSSL=true
    username: martina
    password: Casola7.
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.MySQLInnoDBDialect


server:
  port: 8080